---
abstract: 'REST-like API micro-framework for Perl.'
author:
  - 'Artur Khabibullin - rtkh <at> cpan.org'
build_requires:
  Test::More: '0.88'
configure_requires:
  Module::Build::Tiny: '0.034'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Raisin
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Carp: '1.20'
  Data::Dumper: '2.131'
  File::Basename: '0'
  File::Path: '0'
  File::Slurp: '0'
  Getopt::Long: '0'
  JSON: '2.90'
  List::Util: '1.34'
  Log::Dispatch: '2.39'
  POSIX: '0'
  Plack: '1.0030'
  Plack::Middleware::CrossOrigin: '0.009'
  Time::HiRes: '1.9724'
  YAML: '0.90'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/khrt/Raisin/issues
  homepage: https://github.com/khrt/Raisin
  repository: https://github.com/khrt/Raisin.git
version: '0.2'
